### PR TITLE
Fixed responsiveness issues for mobile view

### PR DESCRIPTION
**Pull request by barakkenny**
Fixed padding and layout issues 
Adjusted the navbar to prevent it from overlapping content.

### CODE REVIEW

**Comment by Luson045** [comment]
Bro can you remove the changes you made in navbar, as I fixed the navbar myself and I don't want any changes in that as of now, so please keep the rest of the changes and revert the navbar changes also fix the conflicts...

**Comment by Luson045** [comment]
@barakkenny run npm i or yarn install once again to generate package-lock.json and then give pr

**Comment by barakkenny** [comment]
I think there are two more conflicts

**Comment by Luson045** [comment]
to fix the conflicts in package-lock,  fetch the latest changes locally run npm i or yarn install and then create a new pr for UserProfile, you need to address that @barakkenny

**Comment by barakkenny** [comment]
can i submit the pr to another branch e.g luson workflow

**Comment by Luson045** [comment]
@barakkenny that's not even needed, you can delete this pr and create a new pr in this branch only, because the other branch is not in sync with this one

**Pull request closed without merging**
