### PR TITLE
google login implemented

### PR DESCRIPTION
**Pull request by 17arindam**
-added frontend google sign in 
-added backend logic of google sign in using oath2 

issue no #27 

https://github.com/user-attachments/assets/dfc25353-36e3-4b7b-8087-a574104cb913

### CODE REVIEW

**Comment by Luson045** [comment]
@17arindam nice

**Comment by Luson045** [comment]
remove the labtest link in navbar and add a profile icon somewhere in the navbar, to go to the profile page

**Comment by 17arindam** [comment]
@Luson045 can i do this by making another issue?

**Comment by Luson045** [comment]
okay, but fix the conflicts here

**Comment by 17arindam** [comment]
@Luson045 i have resolved conflicts

**Pull request merged**
