### PR TITLE
Added pincode field into login/registration form 

### PR DESCRIPTION
**Pull request by shibasarkar**
Screenshot 2024-10-03 174955

### CODE REVIEW

**Comment by Luson045** [comment]
@shibasarkar  merge conflicts

**Comment by shibasarkar** [comment]
@Luson045 unable to resolve conflicts

**Comment by Trevisx07** [comment]
@shibasarkar Do one thing, Make a new PR with syncing(updating) the branch and close this PR.

**Comment by shibasarkar** [comment]
close the PR

**Pull request closed without merging**
