### PR TITLE
Update emergency route to find the nearest hospital and return appointment details

### PR DESCRIPTION
**Pull request by tanish35**
Added a emergency route which when provided with patient details and their pincode searches for the hospital which is nearest to them in terms of time that is we have included traffic and road blockages also. On the basis of that a appointment is created with the hospital and the user too.

Please add a OPENCAGE_APIKEY in your .env file . It is free for 2500 requests/day . It converts the pincode into lat and long and osrm has been used to find the time taken

### CODE REVIEW

**Comment by Luson045** [comment]
@Somnath-Chattaraj Please leave some comment so i can assign you too

**Comment by Somnath-Chattaraj** [comment]
ok..please assign me

**Comment by Luson045** [comment]
done 👍

**Comment by tanish35** [comment]
image

This is the screenshot you may check it out

**Pull request merged**
