### PR TITLE
modified footer open space.

### PR DESCRIPTION
**Pull request by vidhi-github**
**Aligning "Med Space", "About", "Services", "Contact Us", and "Follow Us On" in the same line using flex.

**Each section's content is displayed under its respective heading.

**Changed the background color to a lighter blue gradient.

**Added black box-shadow above the footer.

I am facing with the favicon issue I guess in the deployment.

### CODE REVIEW

**Comment by Trevisx07** [comment]
@vidhi-github Attach relevant screenshots of the changes done with issue number too.

**Comment by vidhi-github** [comment]
Issue no: 499.

I think I am facing some favicon issue in my project due to which I am getting 404 error.

I had done these changes in my branch::

Aligned "Med Space", "About", "Services", "Contact Us", and "Follow Us On" in the same line using flex.

**Each section's content is displayed under its respective heading.

**Changed the background color to a lighter blue gradient.

**Added black box-shadow above the footer.

**Comment by Luson045** [comment]
@vidhi-github  mention issue no.

**Comment by vidhi-github** [comment]
Issue no is 499.

**Pull request merged**
