### PR TITLE
newsletter frontend and backend done : #542 done 

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
newsletter frontend and backend done : #542 done 
So this is the video first of all -
There is some network lag so website is loading slowly, so not mind that 

https://github.com/user-attachments/assets/ca0be9ec-5da0-48c0-b3e5-cb583aa23098

So you have to keep mind this things -

1. for newsletter option visible in footer is only visible to the admin. Because i think you  don't want that everyone can send the newsletter to the user.

2. you dont have any admin option so you have to set mongodb isAdmin value to true. See this image-

db 2

3. this is newsletter schema for storing newsletter subscribing mail -
database

4. And you need to setup the nodemailer email id and password for sending the emails to the user for that you need smtp mail and password so which you can find its information and store in .env file -
evn

Frontend is decent I think but i have work a lot in this from creating admin middleware to storing admin value and then admin context in frontend and then frontend for newsletter and apis in backend for it. So i have more focused on backend part . If you want any information then i can help you.

### CODE REVIEW

**Comment by Luson045** [comment]
I think we had a component for mails, you can use that instead of writing separate code for mails. And there are some merge conflictals

**Comment by Luson045** [comment]
I think we had a component for mails, you can use that instead of writing separate code for mails. And there are some merge conflicts

**Comment by VinayLodhi1712** [comment]
@Luson045 sir i have solved the merge conflict. Secondly, i have create other api because keep everything separate is a good thing it enhance code readability and this mail component has some separate body so i think it will be a good thing to keep it separately.

Also mentioning again the newsletter page is only allowed for admin role so you have to set your isAdmin to true in mongodb database for that emailid.

**Comment by VinayLodhi1712** [comment]
also your footer is not looking with that background color and the footer section component is not visible so if you want to change it so i can work on it.

**Comment by Luson045** [comment]
@VinayLodhi1712 a=okay. A lot of people are working on the footer issue, so I guess it's not needed as of now

**Pull request merged**
