### PR TITLE
Form validated with proper error messages 

### PR DESCRIPTION
**Pull request by clownfish1805**
Resolved the issue.
If a user clicks "Register" with incorrect or incomplete information/field, specific error messages should be displayed for each field.
Basically it is set with hospital for user type , so the user has to change to User field to add information.

### CODE REVIEW

**Comment by Luson045** [comment]
@clownfish1805 check for once if it is functioning properly and the user is getting registered andis able to log in

**Comment by clownfish1805** [comment]
I have checked and also I have added demo video for reference.
[https://drive.google.com/drive/folders/1M_h_zrS0LjrvyMhoYuPwEy7w0nK9AO5u?usp=drive_link](url)

**Comment by Luson045** [comment]
yeah thats fine but please fix the merge conflict i cannot merge without tht

**Comment by clownfish1805** [comment]
I have resolved the conflict , please check on this.

**Comment by Luson045** [comment]
image
//i guess you made some changes, in existing code... 
this one is how it should look 👇
image
@clownfish1805

**Comment by Luson045** [comment]
center it and reuduce the width of the register and login button

**Comment by clownfish1805** [comment]
@Luson045 I have made the corrections.
1.Centered the login/signup page
2.Reduced the width of register/login.
Please check.

**Comment by Luson045** [comment]
done  👍

**Pull request merged**
