### PR TITLE
Desgin /login page frontend

### PR DESCRIPTION
**Pull request by prathmesh703**
https://github.com/user-attachments/assets/346c7732-4ec1-4d19-9a5b-9a668a5d9ac0

frontend of the login/registration page fixes issue #8

### CODE REVIEW

**Comment by Trevisx07** [comment]
@prathmesh703 Attach the screenshot/video of the changes.

**Comment by prathmesh703** [comment]
@Trevisx07 added video

**Comment by Trevisx07** [comment]
Try to put a gradient background of pink & white as per the main theme in spite of white background and also resolve the conflicts in PR.

**Comment by prathmesh703** [comment]
Screenshot 2024-10-02 150609
is this ok?

**Comment by Trevisx07** [comment]
@prathmesh703 Please create a issue with proper description ensuring that it isn't taken by anyone and then after we would assign & after that you can make a PR. As of now kindly close the PR.

**Comment by prathmesh703** [comment]
this fixes the issue #8 which was assigned to me

**Comment by prathmesh703** [comment]
ok I will work on it

**Pull request closed without merging**
