### PR TITLE
🔒 Enhance password validation with stronger security rules

### PR DESCRIPTION
**Pull request by LitZeus**
### Description

This PR addresses [#294](#) by enhancing password security. It enforces the following validation rules:
- At least one uppercase letter
- At least one number
- At least one special character

These changes strengthen the authentication process, ensuring more secure password creation both in the frontend and backend.

### CODE REVIEW

**Comment by Luson045** [comment]
conflicts

**Comment by Luson045** [comment]
@LitZeus

**Review by LitZeus — COMMENTED** [review]
extra import was detected, it might have left while resolving merge conflicts a few minutes back on github

**Comment by LitZeus** [comment]
@Luson045 Everything has been resolved now.

**Pull request merged**
