### PR TITLE
Fixes:#496 - Allignment of navbar fixed.

### PR DESCRIPTION
**Pull request by Jashwanth-rit**
Fixes:#496
This PR makes sure that Allignment fixes.

Screenshot 2024-10-19 202146

@Luson045 assign my other issues as well , so that i can contribute.

### CODE REVIEW

**Comment by Jashwanth-rit** [comment]
I just cloned your website, like this from you clone itself, 

Screenshot 2024-10-19 205514

 i dint changed any allignment of that it just happened from there itself ,
i think it varies , if clone it . or varies by system.

**Comment by Trevisx07** [comment]
@Jashwanth-rit Oh okay.

**Comment by Trevisx07** [comment]
image
Do one thing put your screen at 100% zoom and then fix the issue you had solved for 110% zoom.

**Comment by Jashwanth-rit** [comment]
ohh ok , I do.

**Pull request merged**
