### PR TITLE
Improved  Landing Page and Research and Data Section

### PR DESCRIPTION
**Pull request by ParasY1724**
**Issue No:** #103 
**Description:**
-Added Framer-Motions
-Floating Icons 
-Improve Gradient
--Avoided Using Direct Images:
-Added Table Component
-Added PieChart Component

**Output:**

https://github.com/user-attachments/assets/bbb1ceb9-4af2-497c-8e17-f9b63f4a9579

### CODE REVIEW

**Comment by Luson045** [comment]
Make it responsive and revert the changes made in user review section

**Comment by ParasY1724** [comment]
@Luson045 ok , i will make it responsive

**Comment by ParasY1724** [comment]
@Luson045  Changes Done , Have a look
**Responsiveness: **
https://github.com/user-attachments/assets/f97245ad-e74c-4db1-91c1-e4fa2be1305f

**Comment by Luson045** [comment]
Fix this graph

**Pull request merged**
