### PR TITLE
Improve Cursor Effect for Enhanced User Experience.

### PR DESCRIPTION
**Pull request by AnkitLuhar**
### Issue Addressed:

This PR addresses Issue No. #155

### **Changes Made:**

**1>Enhanced Cursor Behavior:**

- Improved the cursor effects to provide a smoother experience when hovering over elements. The updated cursor design creates a more visually appealing interaction.

**2>Button Interaction Feedback:**

- Added CSS properties to enhance the button click effect. The new styles provide a more tactile feedback experience, making it feel as if the button is being pressed when clicked. This improvement aims to offer a user-friendly feel when interacting with buttons.

Here is the ScreenRecording:

[screen-capture (10).webm](https://github.com/user-attachments/assets/c61e2ef8-b9b0-4251-ac35-93400069b717)

### CODE REVIEW

**Comment by AnkitLuhar** [comment]
@Luson045 conflicts is resolved

**Comment by Luson045** [comment]
@AnkitLuhar  you have changed the insights and analysis section right?? 




These data are not meant for what's written in the title, just add these back to where it was, below the services section add a research and analysis section and add all the graphs and tables that were present there.. ASAP.

**Comment by AnkitLuhar** [comment]
@Luson045 sry for that changes,kindly please revert the PR!

**Comment by AnkitLuhar** [comment]
@Luson045 wait

**Comment by AnkitLuhar** [comment]
@Luson045 opening one more PR which address the Issue No. #156 , in this it will fixed

**Pull request merged**
