### PR TITLE
Feat : Added spinner for registration

### LINKED ISSUE #404: [Feat] : Add loader during registration
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently we do not show any action when user clicks on register button which leave user in question whether he/she clicked `Register` button or not and again clicks `Register` button which sends multiple requests to the server  which in return throws a error.  So A loader will give a visual indication of some process and to wait to finish it.

### Use Case

Will help user during registration. 

### Benefits

_No response_

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by lade6501**
Closes #404 

Changes in PR
- Added spinner for registration
- Added validation to back button 
   So that user is not able to go back to previous step once he clicks on `register` button.
- Consistent with dark theme

Demo:

https://github.com/user-attachments/assets/23a87476-1267-491b-98d8-9dfb4ba11a51

### CODE REVIEW

**Review by Trevisx07 — APPROVED** [review]

**Comment by Luson045** [comment]
yo @lade6501 can you change the genders to title case

**Comment by lade6501** [comment]
> yo @lade6501 can you change the genders to title case

Added 👍

**Comment by Luson045** [comment]
@lade6501 and also add the spinner for login, someone moved the spinner to bottom left 😵

**Comment by lade6501** [comment]
> @lade6501 and also add the spinner for login, someone moved the spinner to bottom left 😵

Shall I make it same as that of register or previous circle loader ?

**Comment by Luson045** [comment]
@lade6501 i think previous circle would be right, idk whose pr it was but things are pretty messed up, even the instant opd link is redirecting to registration form 😆, just keep the previous loader and place it in the center

**Comment by lade6501** [comment]
I think it's working fine, @Luson045  could you confirm ?

**Comment by Luson045** [comment]
@lade6501  yeah I've been fixing some of them, 😅 you can give pr, I'll merge by morning

**Comment by lade6501** [comment]
Hi @Luson045 any changes required in this PR ?

**Pull request merged**
