### PR TITLE
Added new Page for terms

### PR DESCRIPTION
**Pull request by devanshar**
Added New Page  for terms with eye-catchy design

{8198872B-70BD-4DBB-ABD4-D08A4A9C354E}

{301974C8-B111-43AD-8F3A-5111A0C79472}

### CODE REVIEW

**Comment by devanshar** [comment]
please label this under gssoc-ext and hactoberfest

**Comment by Luson045** [comment]
conflicts!

**Comment by devanshar** [comment]
> conflicts!

Done

**Comment by Luson045** [comment]
wait  wait, when did i assigned this issue to you?? mention the issue please

**Comment by Luson045** [comment]
fine, but won't accept the next time... 👍

**Comment by devanshar** [comment]
> fine, but won't accept the next time... 👍

Thanks, Will take care from next time

**Pull request merged**
