### PR TITLE
Instant OPD card and redirecting to user profile on confirmation of appointment

### PR DESCRIPTION
**Pull request by 17arindam**
- i have created OPD card that is containing the response data of the form 
- on confirming a appointment the user is redirected to User Profile .
Screenshot 2024-10-05 231654

### CODE REVIEW

**Comment by 17arindam** [comment]
@Luson045 please review my pr issue no #159

**Comment by Luson045** [comment]
great work @17arindam add one more thing, let the user print it if he/she wants to, create a blob file and let the user print/download these details in pdf format. This way it can also be used in hospital OPD section too

**Comment by 17arindam** [comment]
@Luson045 
Screenshot 2024-10-06 031023
Screenshot 2024-10-06 031041
please check my updates

**Comment by Luson045** [comment]
@17arindam great 👍\

**Pull request merged**
