### PR TITLE
[Feat] Redesign Form Layout in registerOPD page for Better Usability, Visual Appeal, and Responsiveness 

### LINKED ISSUE #333: [Feat] Redesign Form Layout in registerOPD page for Better Usability, Visual Appeal, and Responsiveness
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- On desktop, redesign the form to display two input fields per line to reduce height.
- Some input fields (e.g., Reason) will take full width for better visual balance.
- On mobile, stack all 11 input fields vertically for easy navigation.
- Example: place the two input fields like this (input design will not be change)-
Screenshot 2024-10-09 192829

### Use Case

Users filling out the form will experience a more organized layout on desktop, reducing form height and enhancing readability. On mobile, users will have a streamlined, stackable layout, ensuring the form remains accessible and easy to use.

### Benefits

- Improved form usability and visual appeal.
- More compact and efficient layout on desktop.
- Full responsiveness across devices, enhancing user experience on mobile and tablet.
- Better alignment with modern UI standards, reducing visual clutter.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Md-SabbirHosen**
### Linked Issue:
- Closes #333

### Feature Description:
- Redesigned the form layout in the registerOPD page for better usability, visual appeal, and responsiveness.
- On desktop, form now displays two input fields per line to reduce height.
- Some fields (e.g., Reason) take full width for better visual balance.
- On mobile and tab device all input fields are stacked vertically for easy navigation.

### Benefits:
- Improved form usability and visual appeal.
- More compact layout on desktop and fully responsive on mobile.
- Better alignment with modern UI standards.

### Update UI:

https://github.com/user-attachments/assets/e0098617-4c96-41c7-a22c-5d504894ee84

### CODE REVIEW

**Comment by Luson045** [comment]
conflicts!!

**Comment by Md-SabbirHosen** [comment]
Ok, I'll resolve it very soon

**Comment by Md-SabbirHosen** [comment]
@Luson045  can you please help on how do I deployment successful. I already resolve the conflict. Is it necessary for passing vercel deployment check for mergin pull request?

**Comment by Luson045** [comment]
@Md-SabbirHosen 
image

**Pull request closed without merging**
