### PR TITLE
Separate Contact Us page added 

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
Issue no : #214 
Contact Us added to footer

https://github.com/user-attachments/assets/651c536d-ecdb-4d19-bff2-fa8c3f80a189

By closing PR #380  I raise this new PR.
I solved all errors now there is no error in build.

Medi connect Build

### CODE REVIEW

**Comment by AbhijitMotekar99** [comment]
Hey @Luson045 
Now please merge this PR because its blocking me from working on other issues.

**Comment by Luson045** [comment]
@AbhijitMotekar99 conflicts

**Comment by Luson045** [comment]
@AbhijitMotekar99 cannot assign level3

**Comment by AbhijitMotekar99** [comment]
> @AbhijitMotekar99 conflicts

Conflicts resolved

**Comment by Luson045** [comment]
there might be some issue when resolving conflicts as deployment failed, check again if there is some error

**Pull request closed without merging**
