### PR TITLE
fixed dark mode and alignment #430

### PR DESCRIPTION
**Pull request by c4dr-me**
Now the about section has proper alignment for all cards
Community says section is fixed for dark mode

https://github.com/user-attachments/assets/86ae20d7-055d-48d1-915d-a8b928ecfe2d

### CODE REVIEW

**Comment by c4dr-me** [comment]
@Luson045 can u review the pr
thanks.

**Comment by Luson045** [comment]
conflicts, fix it please

**Comment by c4dr-me** [comment]
@Luson045 resolved the conflicts

**Comment by c4dr-me** [comment]
also please add necessary labels for gsoc and hacktoberfest resp before merging

**Comment by c4dr-me** [comment]
> also please add necessary labels for gsoc and hacktoberfest resp before merging

@Luson045

**Pull request merged**
