### PR TITLE
Added terms page

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
#Fixed Issue : #236

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@Luson045 please add the labels and assign to me

**Comment by Rizvi-Faiz** [comment]
@luson my other pr #262  is not labeld and is not assigned to me please do that to

**Comment by Luson045** [comment]
@Rizvi-Faiz sorry i didn't noticed... anyway there are still conflicts.... and it's past 1 now

**Comment by Rizvi-Faiz** [comment]
@Luson045  but i gave pr before 12 and if you had seen then i would have resolved the branch conflict can you merge it now and add the labels

**Comment by Luson045** [comment]
are you sure? this pr still have conflicts. and deployment has failed.

**Comment by ROKUMATE** [comment]
@Rizvi-Faiz resolve the conflicts by today night ... else we would have to close this pr

**Comment by Rizvi-Faiz** [comment]
@ROKUMATE sure sir

**Comment by Rizvi-Faiz** [comment]
@ROKUMATE i am having a lot of errors 
So I am thinking to make a new PR .

**Pull request closed without merging**
