### PR TITLE
Icons Added in Footer #149

### PR DESCRIPTION
**Pull request by anmol-284**
Animated Icons has been added in the footer section. please have a look at the video sample
[sample.webm](https://github.com/user-attachments/assets/70977761-5ee7-48e7-8c6d-a062d4d7dfbd)

### CODE REVIEW

**Comment by anmol-284** [comment]
Please add hacktoberfest 2024 label

**Comment by Luson045** [comment]
fix the conflicts else i cannot merge @anmol-284

**Comment by anmol-284** [comment]
fixed the conflicts, please look into it

**Comment by Luson045** [comment]
@anmol-284 check if every feature is functional in your local setup, and inform here. If it is then i'll merge

**Pull request merged**
