### PR TITLE
feat: issue: #44 Create HospitalCard Component with mock data and responsive design

### PR DESCRIPTION
**Pull request by varma-101**
- Implement reusable HospitalCard component to display hospital details (name, location, contact info, rating)
- Add mock data for UI testing and development
- Ensure responsive layout for various screen sizes
- Apply clean and modern styles using CSS/Material UI
- Add placeholder for future backend API integration

### CODE REVIEW

**Comment by Luson045** [comment]
@varma-101 fix conflicts remove the changes from your side in index.html

**Comment by varma-101** [comment]
image

**Comment by Luson045** [comment]
bro the navbar?? @varma-101

**Comment by varma-101** [comment]
> bro the navbar?? @varma-101

I didn't changed it.

**Comment by Luson045** [comment]
Update your repo with the latest changes @varma-101

**Pull request closed without merging**
