### PR TITLE
Enhanced Login and signup page colors : Issue no #203

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
Enhanced colors of login and register now it matches to overall website colors

## Before
Before login medi-connect

## After
Medi-connect

Medi connect register

### CODE REVIEW

**Comment by Luson045** [comment]
conflicts

**Comment by AbhijitMotekar99** [comment]
Now I resolved conflicts

**Comment by Luson045** [comment]
there are conflicts in package-lock, run npm install locally it will be fixed

**Comment by AbhijitMotekar99** [comment]
Hey @Luson045 
I had already installed the node modules, but there were 264 conflicts in the package-lock.json file. So, I deleted it, as it's not necessary. Anyone who wants to run the project can simply do npm install locally to regenerate the package-lock.json file.

**Comment by Luson045** [comment]
@AbhijitMotekar99 damn bro 😂, actually it violates the header rule and some other in github i dont know but without that i cannot merge.. so yeah just run npm install locally and push the changes it'll be fixed

**Comment by AbhijitMotekar99** [comment]
Ok bro I will raise PR again

**Pull request closed without merging**
