### PR TITLE
Modified README.md file

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Issue Resolved

- Issue #363 

# Feature Description

### 1) Added animated line separators
Added animated line separators in between sections and also add the GSSoC 2024 Extended & Hacktoberfest accepted image for Contributors to know that this repository is officially accepted for the programs.

image

### 2) Replaced the Contact section  with a **Team section**

- Before
image

- After
image

### 3) Modified the Contributors mention section:
- Before
image

- After
image

# Reference Video

https://github.com/user-attachments/assets/18439e01-7973-4ced-9568-e89a9933cdd7

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Please review the PR and assign it to me with the necessary labels.

**Comment by Luson045** [comment]
@rajdeepchakraborty-rc  okay looks good 👍

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc okay looks good 👍

Thanks for reviewing the PR.

**Comment by rajdeepchakraborty-rc** [comment]
@Luson045 Will you close the issue #363 since the PR has been merged?

**Pull request merged**
