### PR TITLE
Improve Cursor Effect for Enhanced User Experience.

### PR DESCRIPTION
**Pull request by AnkitLuhar**
### Issue Addressed:

This PR addresses Issue No. #155

### **Changes Made:**

**1>Enhanced Cursor Behavior:**

- Improved the cursor effects to provide a smoother experience when hovering over elements. The updated cursor design creates a more visually appealing interaction.

**2>Button Interaction Feedback:**

- Added CSS properties to enhance the button click effect. The new styles provide a more tactile feedback experience, making it feel as if the button is being pressed when clicked. This improvement aims to offer a user-friendly feel when interacting with buttons.

Here is the ScreenRecording:

[screen-capture (10).webm](https://github.com/user-attachments/assets/c61e2ef8-b9b0-4251-ac35-93400069b717)

### CODE REVIEW

**Comment by Luson045** [comment]
disable it in android use and make sure when the cursor is stoped, no dots is left on the screen @AnkitLuhar 
image
image

**Comment by AnkitLuhar** [comment]
@Luson045 ohk, opening one more PR in this it will be fixed. related to Issue No. #156

**Comment by AnkitLuhar** [comment]
@Luson045 the Issue No. #156 implementation + above requirement is resolved in the added3 commit 

here is the ScreenRecording:
[screen-capture (11).webm](https://github.com/user-attachments/assets/f48e5851-9d82-4dfe-a5d6-2b1e60b7574e)

**Comment by AnkitLuhar** [comment]
@Luson045 kindly merge this PR so, i can Open PR for the issue No. #156 ,currently unable to open the PR for this ,so all the implementation is added in the commit "added3"

**Comment by Luson045** [comment]
Cool @AnkitLuhar , merge conflicts, I'll merge the changes tomorrow

**Comment by AnkitLuhar** [comment]
@Luson045 ohk

**Comment by AnkitLuhar** [comment]
@Luson045 unable to resolve the conflicts,kindly please help to resolve this conflicts 

image

**Comment by Luson045** [comment]
@AnkitLuhar I'll look at it tomorrow 👍🏻👍🏻

**Comment by AnkitLuhar** [comment]
@Luson045 hey, closing this PR and Making the just replicate of it....in which it addresses the Issue No. #155

**Comment by AnkitLuhar** [comment]
@Luson045 , now you can merge the latest commit i made ,in this its properly fixes all the issues regarding the Issue No. : #155
( loader part is not included in this commit)

**Comment by Luson045** [comment]
image
still showing conflicts, i recommend you to open a new pr

**Comment by AnkitLuhar** [comment]
@Luson045  recently i opened the new PR but its, having the same Conflicts Issue.

**Pull request closed without merging**
