### PR TITLE
Added pincode to registration page

### PR DESCRIPTION
**Pull request by shibasarkar**

### CODE REVIEW

**Comment by Luson045** [comment]
@shibasarkar Bro you have changed the design of the form.. 
and the forget password is not even working, you can just copy the current layout and add your changes there
image
image

otherwise I cannot merge it

**Comment by Luson045** [comment]
@shibasarkar you can skip this and work on the other issue that was assigned to you.

**Comment by Luson045** [comment]
bro update your repo before giving pr, this pr is missing a lot of changes that were made, accepting this pr is like reverting all those changes, update your local repo and then make changes

**Comment by shibasarkar** [comment]
Close

**Pull request closed without merging**
