### PR TITLE
Changed Registration form according user type

### LINKED ISSUE #105: Change the registration form according to the details required for the hospital and users
as both hospital and user have different fields i their database, we need to handle taking those details when a hospital or a user registers... You can find the required fields in server/model  just add input for the items which are there in the model but not in the UI

example we need to take input of PIN code from the hospital but it is not there in the register page as of now..

first  you can merge conflicts of your previous pr and then you can do this one

_Originally posted by @Luson045 in https://github.com/Luson045/medi-connect/issues/70#issuecomment-2389052029_

### PR DESCRIPTION
**Pull request by lade6501**
fixes #105 

Changes in the PR 
- Created separate components for `Login` and `Register`
- Added multistep form for `Register`
- Added zod validation for Hospital schema 
-  Added zod validation for User schema 

Demo 1:

https://github.com/user-attachments/assets/d771556f-ddef-43f5-863d-c769af606cc2

Demo 2:

https://github.com/user-attachments/assets/f20a5dde-990a-40b6-ae23-fb4f9dd03004

### CODE REVIEW

**Comment by Luson045** [comment]
there are some error's causing issue in deployment, kindly fix tht

**Comment by lade6501** [comment]
I tried checking in vercel, but doesn't have access.

**Comment by Luson045** [comment]
maybe some issues with package.json conflicts, you can delete this pr run npm install or yarn install loclly 
and give a new pr, also there's a new feature of a card shown after successful instant opd registration make sure that is not reverted

**Comment by lade6501** [comment]
Sure

**Comment by Luson045** [comment]
make sure you fetch the newest  changes before giving the next pr, i think you should do it tomorrow morning as i have to merge other pr's so conflicts may occur again , so better fetch the latest change tomorrow, run npm install and then give a new pr

**Comment by lade6501** [comment]
> make sure you fetch the newest changes before giving the next pr, i think you should do it tomorrow morning as i have to merge other pr's so conflicts may occur again , so better fetch the latest change tomorrow, run npm install and then give a new pr

Had taken latest changes before PR.

**Comment by Luson045** [comment]
the thing is i am merging the unmerged pr's so new changes will be there after that, so it's better to do it after that, so that no conflicts occur

**Pull request closed without merging**
