### PR TITLE
Email will be sent after booking an appointment

### PR DESCRIPTION
**Pull request by Somnath-Chattaraj**
Solution of issue #66 

file added 
`server/modules/mail/sendMail.js`

using smtp server of gmail for sending email to the users

### CODE REVIEW

**Comment by Luson045** [comment]
this was the frontend issue so please consider the work on the frontend too, like instant OPD is not working currently, so implement both frontend and backend, backend is done, now integrate it with the frontend

**Comment by Somnath-Chattaraj** [comment]
updated frontend form. @Luson045

**Comment by Luson045** [comment]
image
@Somnath-Chattaraj you're not taking email as an input, how are you sending the mail then, and there are some issues in the frontend where the registration is not going properly...

Take a look at this ------> issues in instant OPD feature #68

**Comment by Somnath-Chattaraj** [comment]
ok...i will solve it

**Pull request merged**
