### PR TITLE
 Fixed the text disappears on hover effect and did mini changes

### PR DESCRIPTION
**Pull request by subrataCS**
fix that small hover issue, But I can't find the page load time issue its just working fine.

### CODE REVIEW

**Comment by Trevisx07** [comment]
@subrataCS Please mention the issue number and add pic/video whatever changes done.

**Comment by subrataCS** [comment]
issue number #327 

image

**Comment by Trevisx07** [comment]
@subrataCS Can you enhance the load time of the page. Means it takes too short time to load.
For example you can add smoothening effect on opening as there is in the About page.

**Comment by subrataCS** [comment]
sure , thanks for explain , I'm working on it now.

**Comment by subrataCS** [comment]
Issue number: #327 

Loading: I added a smooth fade effect when loading the page for the first time. When clicking the "load more" button, I add another fade effect when loading new items.

Hover Effect: Fix the load more button hover issue (text disappears).

UI: Did mini changes to UI.

**Comment by subrataCS** [comment]
issue no. #327 

Navbar added to the Lab page

**Pull request merged**
