### PR TITLE
fix the navbar hide on scroll down, show on scroll up with dark mode and responsive menu 

### LINKED ISSUE #358: [Bug] someone made the navbar sticky
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

the navbar used to move up when scrolled down and move down when scrolled up, now in some recent changes, someone changed it to be sticky, you need to fix it in this issue also navbar is looking very full fix it too.
image

### Add Screenshots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC contributor
- [x] I want to work on this issue (Optional)
- [x] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Suraj-kumar00**
This PR fixes #358

- Restored navbar scroll behavior (hide on scroll down, show on scroll up).
- Simplified navbar layout to reduce clutter.
- Improved mobile menu responsiveness.

### CODE REVIEW

**Comment by Luson045** [comment]
image
this looks diistorted, please keep the design professional
like this 👇
image

**Comment by Suraj-kumar00** [comment]
> image this looks diistorted, please keep the design professional like this 👇 image

oh let me see !

**Comment by Suraj-kumar00** [comment]
> image this looks diistorted, please keep the design professional like this 👇 image

Please check now

Screenshot from 2024-10-11 01-24-27
Screenshot from 2024-10-11 01-24-43
Screenshot from 2024-10-11 01-24-53
Screenshot from 2024-10-11 01-24-59

**Comment by Suraj-kumar00** [comment]
Hi @Luson045, can you please review now the changes?

**Comment by Luson045** [comment]
There's still a gap in the preview and idk why the deployment is getting cancelled again and again give a new pr, if the gap issue is fixed.

**Comment by Suraj-kumar00** [comment]
> There's still a gap in the preview and idk why the deployment is getting cancelled again and again give a new pr, if the gap issue is fixed. 

Okay I'll update soon.

**Comment by Suraj-kumar00** [comment]
> There's still a gap in the preview and idk why the deployment is getting cancelled again and again give a new pr, if the gap issue is fixed. 

Hi @Luson045, I just noticed that the screenshot you have shared in not of localhost?
And without merging this pull request how are the changes that I made are reflecting in the main branch?

Please merge the changes I have share you the mobile view responsiveness it working fine.

**Comment by Luson045** [comment]
well vercel provides a preview of the changes, why should i merge something that works only on localhost..

**Comment by Luson045** [comment]
@Suraj-kumar00 and even this issue is already fixed, I just didn't wanted your work to go to waste, but okay this issue have taken too long, I'm closing it. You can work on other issues..

**Pull request closed without merging**
