### PR TITLE
Upstyled the review cards

### LINKED ISSUE #58: Redesigning the Review section
image

### PR DESCRIPTION
**Pull request by ayush-848**
closes #58

image

### CODE REVIEW

**Comment by ayush-848** [comment]
@Luson045 please check this

**Comment by Luson045** [comment]
@ayush-848  is it auto scrolling, like can you check the current user review section 
https://medi-connect-in.netlify.app/
i think this one's better

**Comment by ayush-848** [comment]
> @ayush-848 is it auto scrolling, like can you check the current user review section https://medi-connect-in.netlify.app/ i think this one's better, just do one thing, fix this shadow issue image shadow not showing up for first 2 cards

My one is autoscroll
Also I forgot to make it responsive which I will do now

**Comment by Luson045** [comment]
okay and please remove the border and add light shadow effect instead

**Comment by Luson045** [comment]
keep it minimalistic

**Comment by ayush-848** [comment]
image

image

**Comment by Luson045** [comment]
The next button is not properly moving to the next card in Android view

**Comment by ayush-848** [comment]
> 
> 
> The next button is not properly moving to the next card in Android view

Ok, will fix it

**Comment by Luson045** [comment]
Just take reference from the current one

https://medi-connect-in.netlify.app/
It is already so clean that I can't assign changes unless your design is better.

**Pull request merged**
