### PR TITLE
Separate Contact Us page added 

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
Issue no : #214 

contact us medde

Hey @Luson045 
I have successfully created a separate Contact Us form and integrated social media links. The entire process was somewhat challenging and time-consuming, particularly in ensuring the design and functionality were seamless. Given the complexity of this task and the effort involved, I kindly request that my contribution be upgraded to a **level 3 label.**

### CODE REVIEW

**Comment by 4F24L** [comment]
Always mention the issue no in PR description. Not in the title.

- Fixes #214

**Comment by ROKUMATE** [comment]
it was not that hard page to create ... we cant give level 3 tag to it ... 
resolve the conflicts and we will assign it a Level 2 tag

**Comment by AbhijitMotekar99** [comment]
Hey @Luson045  @ROKUMATE 
I encountered complex merge conflicts in my current pull request that are challenging to resolve in the editor. As a result, I would like to close this PR and raise a new one once I have addressed the conflicts in my local branch.

**Comment by Luson045** [comment]
@AbhijitMotekar99 okay raise new pr, can't give level3 for this

**Pull request closed without merging**
