### PR TITLE
Style Authform

### PR DESCRIPTION
**Pull request by alexander784**

### CODE REVIEW

**Comment by Luson045** [comment]
attach a screenshot of changes being made and resolve conflicts

**Comment by alexander784** [comment]
Screenshot from 2024-10-02 10-46-39
Screenshot from 2024-10-02 10-46-18

**Comment by Trevisx07** [comment]
@alexander784 Resolve the conflicts and will tag the labels.

**Comment by Luson045** [comment]
@alexander784 no issues have been assigned to you I guess, and this PR is the same as the another one which is currently active
@Trevisx07 should we accept both?

**Comment by alexander784** [comment]
Screenshot from 2024-10-02 12-25-40
Can't resolve.

**Comment by alexander784** [comment]
> @alexander784 no issues have been assigned to you I guess, and this PR is the same as the another one which is currently active @Trevisx07 should we accept both?

Yes, yes I got no issue.

**Comment by Trevisx07** [comment]
@Luson045 No, We can't accept as of now.
@alexander784 Please create a issue with proper description ensuring that it isn't taken by anyone and then after we would assign & after you can make a PR attaching screenshot/video of the changes done. As of now kindly close the PR.

**Pull request closed without merging**
