### PR TITLE
Use pincode validator to check for valid pincodes

### PR DESCRIPTION
**Pull request by Somnath-Chattaraj**
## Used a npm package to check for valid pincode
 - also solves issue #158 

## Images for reference

 - image with incorrect pincode
Screenshot 2024-10-05 at 12 00 51 PM

- image with correct pincode. Also console log the pincode details
Screenshot 2024-10-05 at 12 01 21 PM

@Luson045  Hopes you find it helpful. Please give it a level Hacktoberfest-accepted

### CODE REVIEW

**Comment by Somnath-Chattaraj** [comment]
@Luson045 do i need to do anything else?

**Comment by Luson045** [comment]
@Somnath-Chattaraj  you weren't assigned this issue... have you read the announcements?

**Comment by Somnath-Chattaraj** [comment]
@Luson045 since it was a long time the assignee has not reponsed with any pr so I did it. A request that please accept this pr or give it a label, since my first pr #63 which i coauthored has not been detched as a pull request in hacktoberfest. Hope you will understand

**Comment by Luson045** [comment]
@hmm okay merge the conflixts

**Comment by Somnath-Chattaraj** [comment]
@Luson045 done

**Comment by Somnath-Chattaraj** [comment]
@Luson045 you merge it as it also check for valid pincodes which is not done in pr #184

**Pull request merged**
