### PR TITLE
added steps in the form

### PR DESCRIPTION
**Pull request by AyushSharma72**
i added steps to the opd register form 

Screenshot (23)

image2:
Screenshot (24)
image3:
Screenshot (25)

it is functioning properly I only changed the form structure  it is sending request to the backend

i faced an error that was due to that i do not have the hospitals database so it cannot find the id of the hospital i am requesting for 
here:
Screenshot 2024-10-28 103104

error:
image

empty database:
Screenshot (22)

with proper database it will  work @Luson045

### CODE REVIEW

**Comment by Luson045** [comment]
@AyushSharma72  there are conflicts, I'll merged but if error occurs then I'll have to cancel merge

**Comment by AyushSharma72** [comment]
> @AyushSharma72 there are conflicts, I'll merged but if error occurs then I'll have to cancel merge

I will resolve

**Comment by AyushSharma72** [comment]
> @AyushSharma72 there are conflicts, I'll merged but if error occurs then I'll have to cancel merge

check now @Luson045

**Comment by Luson045** [comment]
issue no.?

**Comment by AyushSharma72** [comment]
> issue no.?

#541

**Pull request merged**
