### PR TITLE
Pull Request: Refactor OPD Registration Form and Login/Register Form to Use React Hook Form

### PR DESCRIPTION
**Pull request by ShreyasNandanwar**
This pull request proposes refactoring the OPD registration form to utilize `react-hook-form` for improved form handling and validation.

## Proposed Changes

1. **Form Handling**: Implemented `react-hook-form` to manage form inputs and state.

2. **Validation**: Set up validation directly in the `register` method of `react-hook-form`, providing real-time feedback for required fields and specific input patterns (e.g., email and contact number).

3. **Reusable Component**: Introduced a `FormField` component for reusability, simplifying the form structure and reducing code redundancy.

4. **Submission Logic**: Consolidated the submission logic into an `onSubmit` function, which prepares the form data for submission to the backend and manages the loading state during registration.

5. **Error Handling**: Enhanced error handling to provide more informative messages to users.

## Rationale

These changes aim to improve the form's overall performance and usability while enhancing its maintainability and extensibility.

## Testing Performed

- Validated that all form validations work as expected.
- Confirmed that form submission to the backend operates correctly.
- Verified that error handling functions as intended.

## Additional Notes

This refactoring maintains the existing functionality of the form while improving code readability and efficiency. The use of `react-hook-form` reduces boilerplate code and enhances validation capabilities.

Feedback and suggestions for further improvements are welcome.

### CODE REVIEW

**Comment by Luson045** [comment]
mention the issue @ShreyasNandanwar

**Comment by ShreyasNandanwar** [comment]
I apologize for submitting a Pull Request without an associated issue. I understand now that this is not the correct workflow for this project, and I appreciate you bringing this to my attention.

To rectify this mistake, I propose that I create an issue describing the need for refactoring the OPD Registration Form to use React Hook Form. Once the issue is created, I will update this Pull Request to reference that issue.

I assure you that I will follow the correct issue-first workflow for all future contributions. Thank you for your patience as I learn the proper procedures for contributing to this project.

Please let me know if there's anything else I should do to correct this situation.

**Comment by Luson045** [comment]
@ShreyasNandanwar yeah that would be the best 👍, create an issue and make changes to the pr accordingly, also when giving PR share the relevant screenshots.

**Comment by Luson045** [comment]
@ShreyasNandanwar merge conflicts,, remove the changes made in registration.jsx file... thats all fixed

**Pull request closed without merging**
