### PR TITLE
Our services page upgraded.

### PR DESCRIPTION
**Pull request by Jay-1409**
I have added more data and meaning to the Our services page.
image
image

Do suggest any other changes.
Thank you!!
(Hacktoberfest2024 && gssoc extd 2024)

### CODE REVIEW

**Comment by Luson045** [comment]
redirect to the hospital page when clicked on book now, reduce the transparency in the service cards @Jay-1409

**Comment by Jay-1409** [comment]
> redirect to the hospital page when clicked on book now, reduce the transparency in the service cards @Jay-1409

okay boss, will do those changes.

**Comment by Jay-1409** [comment]
@Luson045 By hospital page which page exactly do you mean ?

**Comment by Trevisx07** [comment]
@Jay-1409 The main home page.

**Comment by Jay-1409** [comment]
> @Jay-1409 The main home page.

okayy

**Comment by Jay-1409** [comment]
> @Jay-1409 there are some conflicts
oh I see, I will fix them sorry about that, they weren't there the last time I saw.

**Comment by Jay-1409** [comment]
just give me some time

**Comment by Luson045** [comment]
Okay 👍🏻

**Comment by Jay-1409** [comment]
i treid to resolve the conflicts at my end but without seeing the exact conflict location I was not able to resolve them. 
i am truly sorry.

**Comment by Jay-1409** [comment]
what do you suggest? should i reclone it and try again ?

**Comment by Luson045** [comment]
Keep you r changes somewhere, fetch the latest changes run npm install add your changes and create new pr. It will resolve conflicts.

**Comment by Jay-1409** [comment]
> Keep you r changes somewhere, fetch the latest changes run npm install add your changes and create new pr. It will resolve conflicts.

oh okay let me try that then

**Pull request closed without merging**
