### PR TITLE
FEAT: Logout Confirmation Popup

### PR DESCRIPTION
**Pull request by tejasbenibagde**
**Related Issue: [#200](#200)**

#### Changes:
1. **Added Logout Confirmation Popup:**
   - When the user clicks the logout button, a confirmation popup appears with the message:
     - *"Do you really want to log out?"*
   - The popup includes two buttons:
     - **Yes:** Proceeds with logging out.
     - **No:** Cancels the action, keeping the user logged in.
   - This addition helps prevent accidental logouts and improves the overall usability of the site.

#### Request:
1. **Tags:** Please add the appropriate tags to this PR.
2. **Formatting:** I noticed that running `npm run format` with Prettier made changes to more files than expected. Please remind other contributors to run Prettier before submitting their PRs to avoid this issue in the future.

### CODE REVIEW

**Comment by tejasbenibagde** [comment]
Example ScreenShots: 

logout

**Comment by Luson045** [comment]
conflicts, fix it... and a question!! why are there changes in 29 files for the confirmation card?? @tejasbenibagde

**Comment by tejasbenibagde** [comment]
I already answered why there are many changes. Did you not read the description that I've provided?

**Comment by tejasbenibagde** [comment]
I'll fix conflicts as soon as possible.

**Pull request closed without merging**
