### PR TITLE
Enhanced OPD Form with Report Upload and UX Improvements

### PR DESCRIPTION
**Pull request by ananyag309**
#147 
 I have made the following enhancements to the OPD registration form:

Report Upload Feature: Added an option to upload reports (optional) to the form. This allows patients to attach relevant medical reports if they wish, improving convenience without making it mandatory.

User Interface Improvements: Improved the user experience with better form layout and error handling.

Validation: Enhanced validation for form fields to provide better feedback for users and ensure clean data input.

### CODE REVIEW

**Comment by Luson045** [comment]
Merge conflicts

**Comment by ananyag309** [comment]
@Luson045 ok i will modify the code so that it accept multiple documents

**Comment by ananyag309** [comment]
@Luson045 done , now we can upload multiple files

**Comment by Luson045** [comment]
@ananyag309  is it functioning properly, try filling the form with your mail and see if you recieve a booking confirmation

**Comment by ananyag309** [comment]
@Luson045 i made some changes but register button is not functional

**Comment by Luson045** [comment]
@ananyag309 can't merge until that's fixed

**Review by Trevisx07 — APPROVED** [review]

**Comment by ananyag309** [comment]
@Luson045 @Trevisx07 may i know what changes to be made? I raised the issue to help with UX of the instant form the register button was not functional during that time too. I made proper alignment, made it in center, made available the multiple form submission option  and did many more changes. I am new to it and i have tried but i am not able to make the register button functional, if there is something apart from it in UI that need to be changed please let me know.

**Comment by Luson045** [comment]
@ananyag309 is the register form still not functional?? well try to copy your whole code to gpt and cladue and ask for error, try adding these features too
**this is the api:**
`https://medi-connect-f671.onrender.com/hospitalapi/emergency`
**this is the backend function for this form**
`router.post(
  "/emergency",
  asyncHandler(async (req, res) => {
    const { name, email, age, gender, contact, pincode, reason, date } = req.body;
    console.log("name:", name);
    if (!pincode) {
      return res.status(400).json({ message: "Pincode is required" });
    }

    const results = await geocoder.geocode(pincode + " India");
    if (results.length === 0) {
      return res.status(404).json({ message: "Location not found" });
    }

    const userLat = results[0].latitude;
    const userLong = results[0].longitude;
    const hospitals = await Hospital.find({}, { lat: 1, long: 1, _id: 1 });
    let minTime = Infinity;
    let nearestHospital = null;

    for (let hospital of hospitals) {
      const hospitalLat = hospital.lat;
      const hospitalLong = hospital.long;
      console.log(hospitalLat, hospitalLong);
      const route = await axios.get(
        `https://router.project-osrm.org/route/v1/driving/${userLong},${userLat};${hospitalLong},${hospitalLat}?overview=false`
      );
      const time = route.data.routes[0].duration;
      if (time < minTime) {
        minTime = time;
        nearestHospital = hospital;
      }
    }

    // Check if a user with the provided email already exists
    let profile = await User.findOne({ email });

    if (!profile) {
      // If no user exists, create a new one
      const password = Math.random().toString(36).slice(-8);
      profile = new User({
        name,
        email,
        age,
        password,
        gender,
        phone: contact,
      });
    }

    const appointment = {
      userId: profile._id,
      date,
      reason,
      status: "pending",
    };

    try {
      const hospital = await Hospital.findById(nearestHospital._id);
      hospital.appointments.push(appointment);
      profile.appointments.push(appointment);
      await hospital.save();
      await profile.save();

      console.log(`Your appointment has been booked at ${hospital.name} on ${appointment.date}`);
      await sendMail(
        `Your appointment has been booked at ${hospital.name} on ${appointment.date}`,
        profile.email
      );

      res.status(200).json({
        message: "Appointment booked successfully",
        appointment,
        hospital: {
          id: hospital._id,
          name: hospital.name,
        },
      });
    } catch (error) {
      res.status(500).json({ message: "Error booking appointment", error });
    }
  })
);`

**this is the current functional code try to compare with this** 

`import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import Navbar from '../common/Navbar';
import '../../styles/OPD.css';

function OPDRegistrationForm() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',  // Added email field in the state
    age: '',
    gender: '',
    contact: '',
    address: '',
    department: '',
    pincode: '',  // Added pincode field
    reason: '',    // Added reason field
    date: ''       // Added date field
  });

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  const validate = () => {
    const newErrors = {};
    if (!formData.name.trim()) newErrors.name = 'Name is required';
    if (!formData.email.trim()) newErrors.email = 'Email is required';  // Validation for email
    if (!formData.age || formData.age <= 0) newErrors.age = 'Age must be a positive number';
    if (!formData.gender) newErrors.gender = 'Gender is required';
    if (!formData.contact.match(/^\d{10}$/)) newErrors.contact = 'Contact number must be 10 digits';
    if (!formData.address.trim()) newErrors.address = 'Address is required';
    if (formData.address.trim().length < 5) newErrors.address = 'Address must be at least 5 characters long';
    if (!formData.department) newErrors.department = 'Department is required';
    if (!formData.pincode.trim()) newErrors.pincode = 'Pincode is required';  // Validation for pincode
    if (!formData.reason.trim()) newErrors.reason = 'Reason is required';      // Validation for reason
    if (!formData.date) newErrors.date = 'Date is required';                   // Validation for date

    return newErrors;
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
    setErrors({ ...errors, [name]: '' }); 
  };

  const handleSubmit = (e) => {
    e.preventDefault();
  
    console.log()
    const updatedFormData = {
      ...formData,
      age: Number(formData.age), 
    };
  
    const validationErrors = validate();
  
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    console.log('Validation passed. Submitting form...'); // Debugging log
    setIsSubmitting(true);
    
    axios.post(`https://medi-connect-f671.onrender.com/hospitalapi/emergency`, updatedFormData)
      .then(response => {
        console.log('Successfully registered!', response.data); // Debugging log
        alert('Registration Successful!'); // Optional success feedback
      })
      .catch(error => {
        console.error('There was an error registering!', error);
        alert('Registration failed. Please try again.'); // Optional error feedback
      })
      .finally(() => {
        setIsSubmitting(false);
      });
  
    console.log('Form Data Submitted:', updatedFormData); // Debugging log
};

  

  return (
    <>
      <Navbar />
      <section className="form-container">
        <h2>OPD Registration</h2>
        <form onSubmit={(e) => {console.log("Form submitted"); handleSubmit(e);}} className="opd-registration-form">
          <div className="form-group">
            <label>Name:</label>
            <input
              type="text"
              name="name"
              placeholder="Enter your full name"
              value={formData.name}
              onChange={handleChange}
              required
            />
            {errors.name && <span className="error">{errors.name}</span>}
          </div>

          <div className="form-group">
            <label>Email:</label>
            <input
              type="email"  // Changed input type to email
              name="email"
              placeholder="Enter your email"
              value={formData.email}
              onChange={handleChange}
              required
            />
            {errors.email && <span className="error">{errors.email}</span>} 
          </div>

          <div className="form-group">
            <label>Age:</label>
            <input
              type="number"
              name="age"
              placeholder="Enter your age"
              value={formData.age}
              onChange={handleChange}
              required
            />
            {errors.age && <span className="error">{errors.age}</span>}
          </div>

          <div className="form-group">
            <label>Gender:</label>
            <select name="gender" value={formData.gender} onChange={handleChange} required>
              <option value="" disabled>Select gender</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
            {errors.gender && <span className="error">{errors.gender}</span>}
          </div>

          <div className="form-group">
            <label>Contact Number:</label>
            <input
              type="tel"
              name="contact"
              placeholder="Enter your contact number"
              value={formData.contact}
              onChange={handleChange}
              required
            />
            {errors.contact && <span className="error">{errors.contact}</span>}
          </div>

          <div className="form-group">
            <label>Address:</label>
            <input
              type="text"
              name="address"
              placeholder="Enter your address"
              value={formData.address}
              onChange={handleChange}
              required
            />
            {errors.address && <span className="error">{errors.address}</span>}
          </div>

          <div className="form-group">
            <label>Pincode:</label>
            <input
              type="text"
              name="pincode"
              placeholder="Enter your pincode"
              value={formData.pincode}
              onChange={handleChange}
              required
            />
            {errors.pincode && <span className="error">{errors.pincode}</span>}  
          </div>

          <div className="form-group">
            <label>Department:</label>
            <select 
              name="department" 
              value={formData.department} 
              onChange={handleChange} 
              required
            >
              <option value="" disabled>Select Department</option>
              <option value="cardiology">Cardiology</option>
              <option value="neurology">Neurology</option>
              <option value="orthopedics">Orthopedics</option>
              <option value="pediatrics">Pediatrics</option>
              <option value="gynecology">Gynecology</option>
              <option value="dermatology">Dermatology</option>
            </select>
            {errors.department && <span className="error">{errors.department}</span>}
          </div>

          <div className="form-group">
            <label>Reason:</label>
            <textarea
              name="reason"
              placeholder="Enter the reason for your visit"
              value={formData.reason}
              onChange={handleChange}
              required
            ></textarea>
            {errors.reason && <span className="error">{errors.reason}</span>} 
          </div>

          <div className="form-group">
            <label>Date:</label>
            <input
              type="date"
              name="date"
              value={formData.date}
              onChange={handleChange}
              required
            />
            {errors.date && <span className="error">{errors.date}</span>}  
          </div>

          <button type="submit" className="submit-btn" disabled={isSubmitting}>
            {isSubmitting ? 'Registering...' : 'Register'}
          </button>
          <Link to="/" className="back-button">Back to Home</Link>
        </form>
      </section>
    </>
  );
}

export default OPDRegistrationForm;`

**Comment by ananyag309** [comment]
@Luson045 okay i will try to make changes asap

**Comment by Luson045** [comment]
@ananyag309 make sure the api call is correct, make sure that the required fields are being passed to the api call, in your localhost, run it press ctrl+shift+i ... goto networks.... fill the opd form and try to submit it and see what error is showing up or is any call being made.. check these
image

**Comment by ananyag309** [comment]
> @ananyag309 make sure the api call is correct, make sure that the required fields are being passed to the api call, in your localhost, run it press ctrl+shift+i ... goto networks.... fill the opd form and try to submit it and see what error is showing up or is any call being made.. check these.., double check if the data you entered is valid image

I did this thing when clicked on register it showed registering
opd form

**Comment by Luson045** [comment]
@ananyag309 click on it and show me the message

**Comment by ananyag309** [comment]
@Luson045 entries

**Comment by Luson045** [comment]
first of all age should be greater than 18 and write longer reason and share the screenshot of response page and connect on discord luson_10

**Comment by ananyag309** [comment]
@Luson045 
changed opd

**Comment by Luson045** [comment]
this thing yaar 😥
image

**Comment by ananyag309** [comment]
i searched on gpt it showing server side issue do i need to make some changes ? in server folder?? so if there are any server-side errors 

i am sorry for disturbing so much !!!
pincodee

**Comment by Luson045** [comment]
@ananyag309 i've fixed the code in your Registration.jsx file

your changes are outdated do the foloowing

copy the below codes and paste somewhere, copy the code of OPD.css and paste it somewhere, delete this pull request, fetch the latest changes and then replace the codes of Registration.jsx file with this👇 and OPD.css with the changes you made and give a new pr ASAP.

import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import Navbar from '../common/Navbar';
import '../../styles/OPD.css';

function OPDRegistrationForm() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    age: '',
    gender: '',
    contact: '',
    address: '',
    department: '',
    pincode: '',
    reason: '',
    date: '',
    report: [], 
  });

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  const validate = () => {
    const newErrors = {};
    if (!formData.name.trim()) newErrors.name = 'Name is required';
    if (!formData.email.trim()) {
      newErrors.email = 'Email is required';
    } else {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(formData.email)) {
        newErrors.email = 'Invalid email format';
      }
    }
    if (!formData.age || formData.age <= 0) {
      newErrors.age = 'Age must be a positive number';
    } else if (formData.age < 18) {  // Check if age is less than 18
      newErrors.age = 'Age must be greater than 18';
    }
    if (!formData.gender) newErrors.gender = 'Gender is required';
    if (!formData.contact.match(/^\d{10}$/)) newErrors.contact = 'Contact number must be 10 digits';
    if (!formData.address.trim()) {
      newErrors.address = 'Address is required';
    } else if (formData.address.trim().length < 10) {
      newErrors.address = 'Address must be at least 5 characters long';
    }
    if (!formData.department) newErrors.department = 'Department is required';
    if (!formData.pincode.trim()) {
      newErrors.pincode = 'Pincode is required';
    } else if (!/^\d{6}$/.test(formData.pincode.trim())) {
      newErrors.pincode = 'Pincode must be 6 digits';
    }
    if (!formData.reason.trim()) newErrors.reason = 'Reason is required';
    if (!formData.date) newErrors.date = 'Date is required';

    if (formData.report.length > 0) {
      const allowedTypes = ['application/pdf', 'image/jpeg', 'image/png'];
      const maxSizeInBytes = 5 * 1024 * 1024; // 5MB

      formData.report.forEach((file) => {
        if (!allowedTypes.includes(file.type)) {
          newErrors.report = 'Only PDF, JPEG, and PNG files are allowed';
        }
        if (file.size > maxSizeInBytes) {
          newErrors.report = 'File size should not exceed 5MB';
        }
      });
    }

    return newErrors;
  };

  const handleChange = (e) => {
    const { name, value, files } = e.target;
    if (name === 'report') {
      setFormData((prevData) => ({
        ...prevData,
        report: [...prevData.report, ...Array.from(files)], 
      }));
      setErrors({ ...errors, report: '' }); 
    } else {
      setFormData({ ...formData, [name]: value });
      setErrors({ ...errors, [name]: '' });
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
  
    const validationErrors = validate(); // Assume the same validation logic
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }
  
    setIsSubmitting(true);
  
    // Extract only the required fields to be sent to the backend
    const submissionData = {
      name: formData.name,
      email: formData.email,
      age: formData.age,
      gender: formData.gender,
      contact: formData.contact,
      pincode: formData.pincode,
      reason: formData.reason,
      date: formData.date,
    };
  
    // Make the POST request with only the selected data
    axios
      .post(`https://medi-connect-f671.onrender.com/hospitalapi/emergency`, submissionData)
      .then((response) => {
        console.log('Successfully registered!', response.data);
        alert('Registration Successful!');
        setFormData({
          name: '',
          email: '',
          age: '',
          gender: '',
          contact: '',
          address: '',
          department: '',
          pincode: '',
          reason: '',
          date: '',
          report: [],
        });
      })
      .catch((error) => {
        console.error('There was an error registering!', error);
        alert('Registration failed. Please try again.');
      })
      .finally(() => {
        setIsSubmitting(false);
      });
  };

  return (
    <>
      <Navbar />
      <section className="form-container">
        <h2>OPD Registration</h2>
        <form onSubmit={handleSubmit} className="opd-registration-form">
          <div className="form-group">
            <label htmlFor="name">Name:</label>
            <input
              type="text"
              id="name"
              name="name"
              placeholder="Enter your full name"
              value={formData.name}
              onChange={handleChange}
              required
            />
            {errors.name && <span className="error">{errors.name}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="email">Email:</label>
            <input
              type="email"
              id="email"
              name="email"
              placeholder="Enter your email"
              value={formData.email}
              onChange={handleChange}
              required
            />
            {errors.email && <span className="error">{errors.email}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="age">Age:</label>
            <input
              type="number"
              id="age"
              name="age"
              placeholder="Enter your age"
              value={formData.age}
              onChange={handleChange}
              required
            />
            {errors.age && <span className="error">{errors.age}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="gender">Gender:</label>
            <select
              id="gender"
              name="gender"
              value={formData.gender}
              onChange={handleChange}
              required
            >
              <option value="" disabled>Select gender</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
            {errors.gender && <span className="error">{errors.gender}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="contact">Contact Number:</label>
            <input
              type="tel"
              id="contact"
              name="contact"
              placeholder="Enter your contact number"
              value={formData.contact}
              onChange={handleChange}
              required
            />
            {errors.contact && <span className="error">{errors.contact}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="address">Address:</label>
            <input
              type="text"
              id="address"
              name="address"
              placeholder="Enter your address"
              value={formData.address}
              onChange={handleChange}
              required
            />
            {errors.address && <span className="error">{errors.address}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="pincode">Pincode:</label>
            <input
              type="text"
              id="pincode"
              name="pincode"
              placeholder="Enter your pincode"
              value={formData.pincode}
              onChange={handleChange}
              required
            />
            {errors.pincode && <span className="error">{errors.pincode}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="department">Department:</label>
            <select
              id="department"
              name="department"
              value={formData.department}
              onChange={handleChange}
              required
            >
              <option value="" disabled>Select Department</option>
              <option value="cardiology">Cardiology</option>
              <option value="neurology">Neurology</option>
              <option value="orthopedics">Orthopedics</option>
              <option value="pediatrics">Pediatrics</option>
              <option value="gynecology">Gynecology</option>
              <option value="dermatology">Dermatology</option>
            </select>
            {errors.department && <span className="error">{errors.department}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="reason">Reason:</label>
            <textarea
              id="reason"
              name="reason"
              placeholder="Enter the reason for your visit"
              value={formData.reason}
              onChange={handleChange}
              required
            ></textarea>
            {errors.reason && <span className="error">{errors.reason}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="date">Date:</label>
            <input
              type="date"
              id="date"
              name="date"
              value={formData.date}
              onChange={handleChange}
              required
            />
            {errors.date && <span className="error">{errors.date}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="report">Upload Report (Optional):</label>
            <input
              type="file"
              id="report"
              name="report"
              multiple
              onChange={handleChange}
            />
            {errors.report && <span className="error">{errors.report}</span>}
          </div>

          <div className="form-actions">
            <button type="submit" className="submit-btn" disabled={isSubmitting}>
              {isSubmitting ? 'Registering...' : 'Register'}
            </button>
            <Link to="/" className="back-btn">
              Back to Home
            </Link>
          </div>
        </form>
      </section>
    </>
  );
}

export default OPDRegistrationForm;

**Pull request closed without merging**
