### PR TITLE
improve the navbar and its responsiveness

### PR DESCRIPTION
**Pull request by dhruvjain23**
As this issue assigned to me for improving the Navbar. I done with my task.

I take care all of the requirements during design and develop it. 

- I made it simple but attractive by using Gradient and this is Up to date with all current changes till current time.
- Also added the "About" link to Navbar for navigate to about page. 

Hope, It suits with your requirements. 

Kindly merge this Pull Request under the hacktoberfest and hacktoberfest-accepted label and please give level3. @Luson045 

Thanks Sir.
It may happens that due to compressed video , quality of color seems little bit change, hope you understand as i use gradient, in original it looks better.

https://github.com/user-attachments/assets/8e163ab1-be60-4431-b92c-e6d3b62654d0

### CODE REVIEW

**Comment by dhruvjain23** [comment]
Sir , when I created the pull request , logo did'nt change , it seems , it changed after i done with all of my development, but sir i design it in such a way that after merge this request , you simply can change the link of logo.png and the new logo fits well with the navbar design. Hope you help sir. @Luson045

**Comment by Luson045** [comment]
@dhruvjain23 okay everythings's fine but please change that hover effect, underline and transform-y it doesn't look very great, you can make it darker when hovered or just simply leave it but remvoe this underline and upward movement effect

**Comment by dhruvjain23** [comment]
ok, I do that

**Comment by dhruvjain23** [comment]
Final done.
Updated the hover functionality to darker when hover , also added the new logo by changing the previous one.

Kindly merge this Pull Request . @Luson045

**Comment by Luson045** [comment]
Conflicts not yet resolved!

**Comment by Luson045** [comment]
i had to resolve the conflicts so it's level2 now

**Pull request merged**
