### PR TITLE
Added proper validation and ui for OPD registration form

### PR DESCRIPTION
**Pull request by Kunj05**
**Description**
This PR implements comprehensive validation checks for the OPD Registration Form to enhance user experience and data integrity. The following improvements have been made:

- Mandatory fields for name, age, gender, contact number, address, department, and symptoms.
- Enhanced layout and styling for better usability.
- Clear error message styling for validation feedback.
- Adjusted button states for disabled scenarios.
- Ensure data integrity and improve user experience for OPD service users.

**Additional Notes**
- The code has been tested for functionality and responsiveness.
- I am open to further suggestions and improvements from the maintainers.

### CODE REVIEW

**Comment by Kunj05** [comment]
**Photo** : I have zoomed out and took the photo showing you the ui and see the code for the validation 
Screenshot 2024-10-02 030908

**Comment by Luson045** [comment]
This project has some conflicts can you merge conflicts?

**Comment by Kunj05** [comment]
@Luson045 can u check

**Comment by Luson045** [comment]
@Kunj05 there are some error in instant OPD feature
image
try to fix this

**Pull request merged**
