### PR TITLE
Separate Contact Us page added.

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
Issue no : #214 

contact us medde

### CODE REVIEW

**Comment by ROKUMATE** [comment]
@AbhijitMotekar99 Resolve the conflicts ...

**Comment by AbhijitMotekar99** [comment]
Hey @ROKUMATE 
I am not able to solve the conflicts its shows you can solve it in editor , I also reinstall node modules still its not going can you help me ?

**Comment by Luson045** [comment]
@AbhijitMotekar99  create new pr after fetching latest changes.. maybe there's conflicts in package-lock which usually is very large and cannot be fixed this way

**Comment by Luson045** [comment]
@AbhijitMotekar99  any updates? Or I close this PR?

**Comment by AbhijitMotekar99** [comment]
Hey @Luson045 
I am working on this I will raise PR till tomorrow.

**Comment by AbhijitMotekar99** [comment]
Hey @Luson045 
I raise another PR #380 plz check it once

**Pull request closed without merging**
