### PR TITLE
SMS Notification for booking confirmation

### PR DESCRIPTION
**Pull request by lade6501**
solution #66 

Using `Twilio` library to send a SMS notification to the user. Currently it send notification to verified number due to trial account to send SMS to any number will have to use paid plans.

file added
`server/modules/notifications/sendSMS.js`

### CODE REVIEW

**Comment by Luson045** [comment]
Please comment out the twilo api, we're not using it for now...

**Comment by lade6501** [comment]
> Please comment out the twilo api, we're not using it for now... And merge conflicts

Any other api that we specifically  looking for ?

**Comment by Luson045** [comment]
For now I think email will do..

**Comment by lade6501** [comment]
Shall remove whole file or just comment code inside `server/modules/notifications/sendSMS.js`

**Comment by Luson045** [comment]
Keel this file, comment out all the api call being made to this feature

**Comment by lade6501** [comment]
Update

**Review by Luson045 — APPROVED** [review]

**Pull request merged**
