### PR TITLE
Update registration form for emergency route

### PR DESCRIPTION
**Pull request by Somnath-Chattaraj**
partially solves issue #35 

Screenshot 2024-10-03 at 12 05 34 AM

### CODE REVIEW

**Comment by ROKUMATE** [comment]
@Somnath-Chattaraj ig the issue was for making the backend and other functionalities after doing the OPD registration for the issue no #35 

can you explain what u have done here ?
as i can see you have just added few fields into it for email and address.

**Comment by Luson045** [comment]
@Somnath-Chattaraj give PR only when totally completed, level label will only be assigned for the completion of issue, also you are using old design, make sure that's updated and while working with backend provide the working video or something, as deployment link cannot access the backend

**Comment by Somnath-Chattaraj** [comment]
can you please suggest the changes that i need to make. As i have already update the OPD form and api call

**Comment by Luson045** [comment]
@Somnath-Chattaraj everything's working fine??

**Comment by Somnath-Chattaraj** [comment]
Yeah, I think so, as i have just added some field and not change any backend calls

**Comment by Luson045** [comment]
okay

**Pull request merged**
