### PR TITLE
added dark toggle

### PR DESCRIPTION
**Pull request by Abhi0049k**
This pull request implements a toggle feature to switch between dark mode and light mode across the application. The addition of these themes enhances the user experience by providing users with the flexibility to choose a visual style that suits their preferences and improves accessibility in various lighting conditions.

Related Issue #29 

https://github.com/user-attachments/assets/36eecf3b-366b-40f5-bf64-1cdef8756a0c

Changes Made:
- Added a toggle switch in the navigation bar to allow users to switch between dark mode and light mode.
- Updated styling for all relevant components, including forms, buttons, and headers, to ensure consistent visual representation in both modes.
- Ensured that the toggle state is preserved during user sessions to maintain the selected theme across page reloads.
- Improved the visual hierarchy and readability of text elements in both themes to enhance overall usability.

Impact:
- Users can now enjoy a more personalized experience by selecting their preferred theme.
- Improved aesthetics and accessibility contribute to a better overall interface.

Testing:
- Verified that the toggle functionality works correctly, switching themes without any visual glitches.
- Checked all updated components in both dark mode and light mode to ensure proper styling and functionality.`;

### CODE REVIEW

**Comment by Abhi0049k** [comment]
Hi @Luson045, There is an issue with the frontend because of which was having issues while implementing the dark mode as some of the contributors have used external CSS, some of them have used styled component and some have also used tailwindCSS. Because of this it took me so much time.

**Comment by Abhi0049k** [comment]
How about we use shadcn for styling

**Comment by Luson045** [comment]
@Abhi0049k  also remove the node modules can't merge with that, i was literally shocked to see 390 files changed 😂

**Comment by Luson045** [comment]
@Abhi0049k use shadcn in every page?

**Comment by Abhi0049k** [comment]
@Luson045 If we use shadcn then we just need to worry about dark mode and we can simply focus on styling our component. But the way thing are there in the repo. I have to go to each and every file and then add dark mode feature.

**Comment by Luson045** [comment]
hmm lemme think of that, anyway get rid of the node modules during PR please @Abhi0049k

**Comment by Abhi0049k** [comment]
Hi @Luson045,

I am facing an issue with the dark mode toggle. In the updated repository, some contributors are using styled-components, while previously, others were using TailwindCSS. Could you please ask the contributors to stick to either TailwindCSS or a consistent CSS library?

**Comment by Abhi0049k** [comment]
I'm unsure what to do next because, in the first PR, the dark mode was working fine, with the only issue being with node_modules. However, now there are more components involved, with a mix of both TailwindCSS and styled-components, which is becoming difficult to manage.

**Comment by Abhi0049k** [comment]
It might also be a good idea to recommend using the shadcn UI library, which integrates well with TailwindCSS and could provide consistency in the codebase.

As for dark mode, you can create individual issues for each dark mode implementation, as working on a single webpage's dark mode is already a level 3 issue by itself. Alternatively, I can create these issues for you. Making smaller, incremental changes will help contributors focus on and complete those issues, allowing updates to be made to the main branch before moving on to other components.

**Comment by Abhi0049k** [comment]
Working on the entire frontend's dark mode implementation will take more time, especially with the current issues, and the project will only grow larger in the future.

Please inform the contributors to use only TailwindCSS or another CSS library like shadcn, as it will help maintain a proper structure in the repo.

**Comment by Abhi0049k** [comment]
Please let me know the next steps, as I am unable to work on this issue in its current state. We can create issues for individual pages and then add dark mode to them.

**Comment by Luson045** [comment]
okay, do it only for home page @Abhi0049k

**Pull request closed without merging**
