### PR TITLE
Add OPD Schedule Page

### PR DESCRIPTION
**Pull request by AdityaBavadekar**
#400

### CODE REVIEW

**Comment by Luson045** [comment]
@AdityaBavadekar  share relevant screenshots and explain what changes you made

**Comment by AdityaBavadekar** [comment]
I am currently developing the page table. I will share screenshots once done (today itself).

**Comment by AdityaBavadekar** [comment]
https://github.com/user-attachments/assets/e97c3833-43fc-4301-8caa-6cc564f0f00a

**Comment by AdityaBavadekar** [comment]
I have added a drop down to allow user to select the department and the corresponding department schedule is shown in the table. For this I have added a JSON object with predefined schedule for each department. 

I am currently working on adding disclaimer that the timings may change without notice.

**Comment by AdityaBavadekar** [comment]
image

**Comment by Luson045** [comment]
@AdityaBavadekar I expected some work on the back-end, like we are showing the schedule for treatment, but no hospital is specified, I wanted this schedule to be shown for each hospital, in the profile page the hospital should be able to upload the schedule details. You can skip this part but then your PR won't be of much use for the project, so I can only give level1.

**Comment by AdityaBavadekar** [comment]
Ok, got it. So you want this to be listed in the hospital info page and the doctors listed should also be dynamically added based on each hospital. I am doing it but it will take some time.

**Comment by Luson045** [comment]
@AdityaBavadekar yes the schedules should be in a new page which opens up when clicked on a hospital in the hospitals page and in the hospital's profile page there should be the option to add the schedules.

**Comment by Luson045** [comment]
@AdityaBavadekar in this form only, you can take the availability time slots of the doctor in any format, and show it in the schedule

**Comment by AdityaBavadekar** [comment]
Progress:

image
image

**Comment by Luson045** [comment]
looks cool @AdityaBavadekar

**Comment by AdityaBavadekar** [comment]
https://drive.google.com/file/d/1cRbkZvd0SfRtz13EbDZ_5xikf1wswI6P/view?usp=sharing

@Luson045 You can take a look at this screen recording I made. Since it is very big I had to upload it to google drive. It shows the navigation you told.

**Comment by AdityaBavadekar** [comment]
I have also updated the database url usages. While testing locally, I had change every database url usage to change to my localhost url since this was hard coded in all files. I have changed it now so that there is only 1 file databaseUrls.js which has the base url internally and only exposes a object which is easier to use for eg: databaseUrl.auth.profile this maps to complete url in the base file and not in file where it used.

**Comment by Luson045** [comment]
@AdityaBavadekar great job 👍

**Comment by AdityaBavadekar** [comment]
Just wanted to tell that there are some hospitals pre defined statically in json object in project, they have ids like 1,2 ... the Hospital info page will not work for those because it fetches the data from mongo db database where as these are not in database.
You would have to add those hospitals into db, for it to work.

**Pull request merged**
